services:
  materialized:
    image: materialize/materialized:v0.26.0
    ports:
      - 6875:6875
    healthcheck: {test: curl -f localhost:6875, interval: 1s, start_period: 30s}

  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:1.9
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    stdin_open: true
    tty: true
    healthcheck: {test: nc -z localhost 2181, interval: 1s, start_period: 30s}

  kafka:
    container_name: kafka
    image: quay.io/debezium/kafka:1.9
    links:
    - zookeeper:zookeeper
    ports:
    - 9092:9092
    stdin_open: true
    tty: true
    healthcheck: {test: nc -z localhost 9092, interval: 1s, start_period: 30s}

  postgres:
    container_name: postgres
    image: debezium/postgres
    environment:
      - POSTGRES_DB=default
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - 5000:5432
    volumes:
      - ./conf.sql:/Downloads/example data/dev-telemetry.sql
    stdin_open: true
    tty: true
    healthcheck: {test: pg_isready -q -d postgres -U postgres, interval: 1s, start_period: 30s}

  connect:
    container_name: connect
    image: quay.io/debezium/connect:1.9
    environment:
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      CONFIG_STORAGE_TOPIC: my_connect_configs
      GROUP_ID: '1'
    links:
    - zookeeper:zookeeper
    - kafka:kafka
    - postgres:postgres
    ports:
    - 8083:8083
    stdin_open: true
    tty: true
    healthcheck: {test: curl -f localhost:8083, interval: 1s, start_period: 30s}

  # metabase:
  #   image: metabase/metabase:v0.41.5
  #   depends_on: [materialized]
  #   ports:
  #     - 3030:3000
  #
  # loadgen:
  #   build: loadgen
  #   init: true
  #   depends_on:
  #     mysql: {condition: service_healthy}
  #     debezium: {condition: service_healthy}
  #     kafka: {condition: service_healthy}
  #     schema-registry: {condition: service_healthy}
  # cli:
  #   image: materialize/cli:v0.26.0
  #
  #curl -i -X GET -H "Accept:application/json" localhost:8083/connectors/consumer-connector